//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaiMai.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.OrderInfo = new HashSet<OrderInfo>();
        }
    
        public System.Guid ID { get; set; }
        public string City { get; set; }
        public Nullable<System.Guid> CustomerID { get; set; }
        public Nullable<System.Guid> AreaID { get; set; }
        public string AreaName { get; set; }
        public string Address1 { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<bool> Enable { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<OrderInfo> OrderInfo { get; set; }
    }
}
