//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaiMai.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CookInfo
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string Telephone { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Address { get; set; }
        public string merit { get; set; }
        public string Remarks { get; set; }
    }
}
