//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaiMai.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponUseInfo
    {
        public System.Guid ID { get; set; }
        public string GetPath { get; set; }
        public Nullable<System.Guid> CustomerID { get; set; }
        public Nullable<System.Guid> OrderID { get; set; }
        public string OrderCode { get; set; }
        public Nullable<int> CouponNum { get; set; }
        public Nullable<int> Used { get; set; }
        public Nullable<int> Money { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Remarks { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
