//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaiMai.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourierInfo
    {
        public CourierInfo()
        {
            this.OrderDelivery = new HashSet<OrderDelivery>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> ShopID { get; set; }
        public string ImagePath { get; set; }
        public string Telephone { get; set; }
        public string BarCode { get; set; }
        public Nullable<bool> Enable { get; set; }
        public Nullable<bool> IsSecond { get; set; }
        public string Remarks { get; set; }
    
        public virtual Shop Shop { get; set; }
        public virtual ICollection<OrderDelivery> OrderDelivery { get; set; }
    }
}
