//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaiMai.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Address = new HashSet<Address>();
            this.CouponUseInfo = new HashSet<CouponUseInfo>();
            this.OrderInfo = new HashSet<OrderInfo>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Telephone { get; set; }
        public Nullable<int> Coupon { get; set; }
        public string WeiXinID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string Remarks { get; set; }
    
        public virtual ICollection<Address> Address { get; set; }
        public virtual ICollection<CouponUseInfo> CouponUseInfo { get; set; }
        public virtual ICollection<OrderInfo> OrderInfo { get; set; }
    }
}
