//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaiMai.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodInfo
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> ShopID { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.Guid> CategoryID { get; set; }
        public Nullable<System.Guid> SaleType { get; set; }
        public string SupplyDate { get; set; }
        public Nullable<bool> IsPreferential { get; set; }
        public Nullable<int> PIndex { get; set; }
        public Nullable<bool> Enable { get; set; }
        public Nullable<bool> Visible { get; set; }
        public string Image { get; set; }
        public string Remarks { get; set; }
        public string Remarks1 { get; set; }
    
        public virtual Shop Shop { get; set; }
    }
}
