//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaiMai.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> OrderID { get; set; }
        public Nullable<System.Guid> FoodID { get; set; }
        public string FoodName { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Num { get; set; }
    
        public virtual OrderInfo OrderInfo { get; set; }
    }
}
