//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaiMai.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDelivery
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> OrderID { get; set; }
        public string OrderCode { get; set; }
        public Nullable<System.Guid> ShopID { get; set; }
        public Nullable<System.Guid> CustomerID { get; set; }
        public Nullable<System.DateTime> DeliveryTime { get; set; }
        public Nullable<System.Guid> CourierID { get; set; }
        public Nullable<bool> IsSecondDelivery { get; set; }
    
        public virtual CourierInfo CourierInfo { get; set; }
        public virtual OrderInfo OrderInfo { get; set; }
    }
}
