//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaiMai.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInfo
    {
        public OrderInfo()
        {
            this.OrderDelivery = new HashSet<OrderDelivery>();
            this.OrderItem = new HashSet<OrderItem>();
            this.OrderProblem = new HashSet<OrderProblem>();
        }
    
        public System.Guid ID { get; set; }
        public string Code { get; set; }
        public Nullable<System.Guid> ShopID { get; set; }
        public Nullable<System.DateTime> OrderTime { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public Nullable<System.Guid> CustomerID { get; set; }
        public string CustomerTel { get; set; }
        public string CustomerName { get; set; }
        public string Source { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> RealTotal { get; set; }
        public Nullable<bool> IsProblem { get; set; }
        public Nullable<bool> IsSale { get; set; }
        public Nullable<System.DateTime> RequireTime { get; set; }
        public Nullable<bool> Valid { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> Invoice { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<OrderDelivery> OrderDelivery { get; set; }
        public virtual Shop Shop { get; set; }
        public virtual ICollection<OrderItem> OrderItem { get; set; }
        public virtual ICollection<OrderProblem> OrderProblem { get; set; }
    }
}
